//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTimeX {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageTerms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageTerms() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameTimeX.LanguageTerms", typeof(LanguageTerms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic switching between game profiles ähnelt.
        /// </summary>
        internal static string automaticProfileSwitching {
            get {
                return ResourceManager.GetString("automaticProfileSwitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When enabled, GameTimeX automatically switches the game profile. ähnelt.
        /// </summary>
        internal static string automaticProfileSwitchingToolTip {
            get {
                return ResourceManager.GetString("automaticProfileSwitchingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Note: The game folder path must be specified in the profile! ähnelt.
        /// </summary>
        internal static string automaticProfileSwitchingToolTipNote {
            get {
                return ResourceManager.GetString("automaticProfileSwitchingToolTipNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GameTimeX will be restarted automatically now! ähnelt.
        /// </summary>
        internal static string automaticRestart {
            get {
                return ResourceManager.GetString("automaticRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Image ähnelt.
        /// </summary>
        internal static string changeImage {
            get {
                return ResourceManager.GetString("changeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Backup File ähnelt.
        /// </summary>
        internal static string chooseBackupFile {
            get {
                return ResourceManager.GetString("chooseBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Folder ähnelt.
        /// </summary>
        internal static string chooseFolder {
            get {
                return ResourceManager.GetString("chooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Pic ähnelt.
        /// </summary>
        internal static string choosePic {
            get {
                return ResourceManager.GetString("choosePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Backup Folder ähnelt.
        /// </summary>
        internal static string chosseBackupFolder {
            get {
                return ResourceManager.GetString("chosseBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Backup ähnelt.
        /// </summary>
        internal static string createBackup {
            get {
                return ResourceManager.GetString("createBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a backup of the saved profiles and the saved game time data ähnelt.
        /// </summary>
        internal static string createBackupInfo {
            get {
                return ResourceManager.GetString("createBackupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GameTimeX will be restarted automatically to create the backup! ähnelt.
        /// </summary>
        internal static string createBackupWarning {
            get {
                return ResourceManager.GetString("createBackupWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new profile ähnelt.
        /// </summary>
        internal static string createNewProfile {
            get {
                return ResourceManager.GetString("createNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current key: ähnelt.
        /// </summary>
        internal static string currentKey {
            get {
                return ResourceManager.GetString("currentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First time played: ähnelt.
        /// </summary>
        internal static string firstTimePlayed {
            get {
                return ResourceManager.GetString("firstTimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game folder (opt.) ähnelt.
        /// </summary>
        internal static string gameFolderOverlay {
            get {
                return ResourceManager.GetString("gameFolderOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game time: ähnelt.
        /// </summary>
        internal static string gameTime {
            get {
                return ResourceManager.GetString("gameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General Options ähnelt.
        /// </summary>
        internal static string generalOptions {
            get {
                return ResourceManager.GetString("generalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Backup ähnelt.
        /// </summary>
        internal static string importBackup {
            get {
                return ResourceManager.GetString("importBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import a backup of the saved profiles and the saved game time data ähnelt.
        /// </summary>
        internal static string importBackupInfo {
            get {
                return ResourceManager.GetString("importBackupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GameTimeX will be restarted automatically to import the backup! ähnelt.
        /// </summary>
        internal static string importBackupWarning {
            get {
                return ResourceManager.GetString("importBackupWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key active ähnelt.
        /// </summary>
        internal static string keyActive {
            get {
                return ResourceManager.GetString("keyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key for game monitoring ähnelt.
        /// </summary>
        internal static string keyForGameMonitoring {
            get {
                return ResourceManager.GetString("keyForGameMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last time played: ähnelt.
        /// </summary>
        internal static string lastTimePlayed {
            get {
                return ResourceManager.GetString("lastTimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minutes ähnelt.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor key ähnelt.
        /// </summary>
        internal static string monitorKey {
            get {
                return ResourceManager.GetString("monitorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile name ähnelt.
        /// </summary>
        internal static string profileNameOverlay {
            get {
                return ResourceManager.GetString("profileNameOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties ähnelt.
        /// </summary>
        internal static string properties {
            get {
                return ResourceManager.GetString("properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete ähnelt.
        /// </summary>
        internal static string reallyDelete {
            get {
                return ResourceManager.GetString("reallyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename Profile ähnelt.
        /// </summary>
        internal static string renameProfile {
            get {
                return ResourceManager.GetString("renameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save ähnelt.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search for games here ähnelt.
        /// </summary>
        internal static string searchForGames {
            get {
                return ResourceManager.GetString("searchForGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show current game time session when monitoring ähnelt.
        /// </summary>
        internal static string showCurrentGameTimeSession {
            get {
                return ResourceManager.GetString("showCurrentGameTimeSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die if checked the current session game time is shown below the start/stop monitoring button ähnelt.
        /// </summary>
        internal static string showCurrentGameTimeSessionToolTip {
            get {
                return ResourceManager.GetString("showCurrentGameTimeSessionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show toast notification ähnelt.
        /// </summary>
        internal static string showToastNotification {
            get {
                return ResourceManager.GetString("showToastNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Monitoring ähnelt.
        /// </summary>
        internal static string startMonitoring {
            get {
                return ResourceManager.GetString("startMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop Monitoring ähnelt.
        /// </summary>
        internal static string stopMonitoring {
            get {
                return ResourceManager.GetString("stopMonitoring", resourceCulture);
            }
        }
    }
}
